server:
  port: 8083

spring:
  application:
    name: ms-notification

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: ibrahim.alakbarov2006@gmail.com
    password: lysu snmq hvgy dbbx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.airline.msnotification: DEBUG