server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: n7Gq2HkFi4D1pRcNz6MZtYsKb+uN83LhT9VqXjReJ1c=

logging:
  level:
    org.springframework.cloud.gateway: DEBUG