server:
  port: 8081

spring:
  application:
    name: ms-auth

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/airline_auth_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

# JWT Configuration
jwt:
  secret: n7Gq2HkFi4D1pRcNz6MZtYsKb+uN83LhT9VqXjReJ1c=
  expiration: 86400000 # 24 hours

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      management:
        context-path: /actuator

# Logging
logging:
  level:
    org.airline.msauth: DEBUG
    org.springframework.amqp: DEBUG